language: python

python:
- '3.6'

matrix:
  include:
    - python: 3.9
      dist: xenial

install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt

script:
- flake8
- mypy hardback
- pytest test
