[project]
name = "hardback"
version = "0.9.2"
description = "📓 Hardcopy backups of digital data 📓"
authors = [{ name = "Tom Ritchford", email = "tom@swirly.com" }]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
classifiers = ["Programming Language :: Python :: 3", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: 3.14"]
dependencies = [
    "ebooklib",
    "attrs",
    "cfgs",
    "import-all",
    "pillow",
    "progress",
    "pypng",
    "pyyaml",
    "segno",
]

[dependency-groups]
dev = [
    "coverage",
    "import-all",
    "pytest",
    "pyfakefs",
    "pyupgrade>=3.21.2",
    "ruff>=0.14.14",
    "ty>=0.0.14",
]

[tool.uv]

[tool.uv.build-backend]
module-root = ""


[tool.ruff]
[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
[tool.coverage.run]
branch = true
source = "timedata"

[tool.coverage.report]
fail_under = "58"
skip_covered = true
exclude_lines = ["pragma: no cover", "if False:", "if __name__ == .__main__.:", "raise NotImplementedError"]

